Added fluentd forward capability
bufferapp/node-logger pull request #6
Opened 2016-10-21 11:46 UTC by stevenc81

The PR should allow `node-logger` to have a choice of outputting to `stdout` or `fluentd` forward, both using bunyan logger.

Test cases are added using a Mock fluentd daemon server :)

Would love to borrow @djfarrelly or @hharnisc's eyes on this if that's cool :D

2016-10-26 14:59 UTC, djfarrelly requested changes
I added a couple comments on this to keep in line with the linting/javascript code goals of this project :) LMK if you have questions or thoughts

2016-10-26 14:59 UTC, djfarrelly commented on test/helpers/testHelper.js
> +'use strict';
@stevenc81, we aim to lint this project using `npm run lint`, this file is throwing a bunch of them, we may either want to omit this file or adjust it to match the style lint requires 😄

2016-10-26 14:59 UTC, djfarrelly commented on logger.js
> +    streams: [{ stream: stream }],
With new versions of javascript, we can use shorthand assignment if the variable name is the same as the property name:

``` js
streams: [{ stream }],
```

2016-10-27 21:21 UTC, djfarrelly commented on logger.js
> +  } else {
We likely could remove this else blog if we're setting a default stream above in the `let` declaration.

2016-10-27 21:22 UTC, djfarrelly commented on package.json
> +    "msgpack-lite": "*"
@stevenc81 what version of this package should we use? I try to avoid `*` for versions it could cause tests to fail randomly in the future 😉

2016-10-27 21:23 UTC, djfarrelly approved these changes

2016-10-27 21:24 UTC, djfarrelly commented
Hey @stevenc81, I marked this as approved. Overall it's good, I just would like to add that version in the package.json for the msgpack-lite when this gets merged. Let @hharnisc or I know when this is merged and we can publish to npm 👍

2016-10-31 05:16 UTC, stevenc81 commented
Thanks so much @djfarrelly for the review! Learned a ton about node :D I've added another commit to address the points you mentioned in the last round of review. Would be cool if you or @hharnisc are up to publish to npm. Thanks a ton!

2016-10-31 05:16 UTC, merged